mode: normal    # normal | bayesian
# mode: bayesian    # normal | bayesian

input_jsonl: "../../results/train/preprocess_pattern.jsonl"
output_dir: "../../results/model"

feature_policy_file: "../../results/train/feature_policy.txt"

window_size: 80 
pad_value: -1.0

epochs: 10
batch_size: 64
hidden_dim: 32
latent_dim: 8
bidirectional: false
lr: 0.0005
val_ratio: 0.2
seed: 42

# bayesian 모드에서만 사용
mc_samples: 20
